import { addDays, type DateKey } from '@/logic/dates';
import { isHabitDueOn, isNeverDue, type Frequency } from '@/logic/frequency';
import { HABIT_COLORS } from '@/theme/tokens';

/**
 * Synthetic history for dogfooding and store screenshots.
 *
 * The grid only sells the app once it is FULL — an empty new-user grid is the
 * single worst screenshot this product could ship. This generator produces
 * believable, deterministic history: a seeded PRNG means the App Store
 * screenshot can be regenerated byte-identically months later.
 */

/** Mulberry32 — tiny, fast, and deterministic across platforms. */
export function createRandom(seed: number): () => number {
  let state = seed >>> 0;
  return () => {
    state = (state + 0x6d2b79f5) >>> 0;
    let t = state;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export interface HistoryParams {
  frequency: Frequency;
  today: DateKey;
  /** How far back to generate. */
  days: number;
  /** 0…1 chance a due day was completed. */
  adherence: number;
  /** Guaranteed unbroken run ending today. */
  currentStreak: number;
  seed: number;
}

export function generateCompletionHistory({
  frequency,
  today,
  days,
  adherence,
  currentStreak,
  seed,
}: HistoryParams): DateKey[] {
  if (isNeverDue(frequency) || days <= 0) return [];

  const random = createRandom(seed);
  const dates = new Set<DateKey>();

  for (let offset = days - 1; offset >= 0; offset -= 1) {
    const date = addDays(today, -offset);
    if (!isHabitDueOn(frequency, date)) continue;
    // Recent weeks trend slightly better than old ones — habits build.
    const recencyBonus = (1 - offset / days) * 0.12;
    if (random() < Math.min(0.98, adherence + recencyBonus)) dates.add(date);
  }

  for (let offset = 0; offset < currentStreak; offset += 1) {
    dates.add(addDays(today, -offset));
  }

  return [...dates].sort();
}

export interface DemoHabit {
  name: string;
  icon: string;
  color: string;
  frequency: Frequency;
  adherence: number;
  currentStreak: number;
  days: number;
}

/** A varied line-up: a long daily streak, a quota habit, and a weekday habit. */
export const DEMO_HABITS: DemoHabit[] = [
  {
    name: 'Meditate',
    icon: 'moon',
    color: HABIT_COLORS[0].value,
    frequency: { type: 'daily' },
    adherence: 0.86,
    currentStreak: 34,
    days: 300,
  },
  {
    name: 'Read 20 pages',
    icon: 'book-open',
    color: HABIT_COLORS[3].value,
    frequency: { type: 'daily' },
    adherence: 0.72,
    currentStreak: 9,
    days: 240,
  },
  {
    name: 'Strength training',
    icon: 'activity',
    color: HABIT_COLORS[6].value,
    frequency: { type: 'custom', days: [1, 3, 5] },
    adherence: 0.81,
    currentStreak: 4,
    days: 300,
  },
  {
    name: 'Long walk',
    icon: 'sun',
    color: HABIT_COLORS[4].value,
    frequency: { type: 'weekly', timesPerWeek: 3 },
    adherence: 0.55,
    currentStreak: 2,
    days: 200,
  },
  {
    name: 'No screens after 10',
    icon: 'smile',
    color: HABIT_COLORS[8].value,
    frequency: { type: 'daily' },
    adherence: 0.63,
    currentStreak: 6,
    days: 180,
  },
];
